# Generated by Django 4.2 on 2024-03-15 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Имя автора книги', max_length=255)),
            ],
            options={
                'verbose_name': 'Автор',
                'verbose_name_plural': 'Авторы',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='Наименование категории книг', max_length=255)),
                ('subcategory', models.ForeignKey(blank=True, help_text='Наименование подкатегории книг', null=True, on_delete=django.db.models.deletion.CASCADE, to='books.category')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Название книги', max_length=255)),
                ('isbn', models.CharField(help_text='Код ISBN', max_length=255)),
                ('pages_number', models.PositiveIntegerField(blank=True, help_text='Количество страниц в книге')),
                ('publication_date', models.DateField(blank=True, help_text='Дата публикации книги')),
                ('image_link', models.URLField(blank=True, help_text='Ссылка на фото книги')),
                ('image', models.ImageField(blank=True, help_text='Фотография книги', upload_to='<django.db.models.fields.CharField>/')),
                ('summary', models.TextField(blank=True, help_text='Описание книги')),
                ('description', models.TextField(blank=True, help_text='Подробное описание книги')),
                ('status', models.CharField(choices=[('P', 'PUBLISH'), ('M', 'MEAP')], help_text='Статус книги', max_length=8)),
                ('authors', models.ManyToManyField(related_name='authors', to='books.author')),
                ('categories', models.ManyToManyField(related_name='categories', to='books.category')),
            ],
            options={
                'verbose_name_plural': 'Книги',
                'ordering': ['title', 'isbn'],
            },
        ),
    ]
