# Generated by Django 4.2 on 2024-03-15 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='authors',
            field=models.ManyToManyField(to='books.author'),
        ),
        migrations.AlterField(
            model_name='book',
            name='categories',
            field=models.ManyToManyField(to='books.category'),
        ),
        migrations.AlterField(
            model_name='book',
            name='status',
            field=models.CharField(help_text='Статус книги', max_length=8),
        ),
    ]
