# Generated by Django 4.2 on 2024-03-14 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['name'], 'verbose_name_plural': 'Авторы'},
        ),
        migrations.AddField(
            model_name='book',
            name='image_link',
            field=models.URLField(blank=True, help_text='Ссылка на фото книги'),
        ),
        migrations.RemoveField(
            model_name='category',
            name='subcategory',
        ),
        migrations.AddField(
            model_name='category',
            name='subcategory',
            field=models.ForeignKey(blank=True, help_text='Наименование подкатегории книг', null=True, on_delete=django.db.models.deletion.CASCADE, to='books.category'),
        ),
    ]
