# Generated by Django 4.2 on 2024-03-20 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_alter_book_options_alter_book_authors_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(blank=True, help_text='Фотография книги', upload_to='images/<django.db.models.fields.CharField>/'),
        ),
    ]
