# Generated by Django 4.2 on 2024-03-26 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_alter_book_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='description',
            field=models.TextField(blank=True, help_text='Подробное описание книги', null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(blank=True, help_text='Фотография книги', null=True, upload_to='images/<django.db.models.fields.CharField>/'),
        ),
        migrations.AlterField(
            model_name='book',
            name='image_link',
            field=models.URLField(blank=True, help_text='Ссылка на фото книги', null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.CharField(blank=True, help_text='Код ISBN', max_length=13, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='pages_number',
            field=models.PositiveIntegerField(blank=True, help_text='Количество страниц в книге', null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='publication_date',
            field=models.DateField(blank=True, help_text='Дата публикации книги', null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='summary',
            field=models.TextField(blank=True, help_text='Описание книги', null=True),
        ),
    ]
