# Generated by Django 4.2 on 2024-04-06 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0005_alter_book_description_alter_book_image_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="subcategory",
        ),
        migrations.AddField(
            model_name="category",
            name="parent_category",
            field=models.ForeignKey(
                blank=True,
                help_text="Вышестоящая категория книг",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="books.category",
            ),
        ),
    ]
